### ISSUE TITLE
calc() is "calculated" on compilation

### ISSUE THREAD

**Issue by TixieSalander** [robinparisi/higgcss#11]
Some calc() values (the simple one) is "calculated" by less compiler and I'm not sure it's a good idea when there are pourcent and fixed values.
For example in typography.less: 
```
font-size: calc(1em * .625);
```
become:
```
font-size: calc(0.625em);
```

What do you think?
(To prevent calc() to be compiled, you have to rewrite them in `~'calc()'`.

**Comment by robinparisi** [comment]
Good catch!

**Comment by theotix** [comment]
Fixed with #16
