### ISSUE TITLE
Text in `notif notif--warning` (yellow notif) is hardly readable

### ISSUE THREAD

**Issue by ldidry** [robinparisi/higgcss#15]
The contrast between text and notification block is not big enough to ensure readability.

Please, consider a darker `color`.

For what I tested, `#444` is quite good and apply nicely to the other notifications (success and error), but that's just a hint.

**Comment by TixieSalander** [comment]
Hi, thanks for the feedback. It's now fixed with [38f09bf](https://github.com/robinparisi/higgcss/commit/38f09bff66fba765759260f7cba4b5bbb8c817e3).
